### ISSUE TITLE
Anyone know if this will work on stm32 f2?

### ISSUE THREAD

**Issue by BlackDragon2020** [pingumacpenguin/STM32-O-Scope#14]
I have an extra tft display that has sd card wifi and stem32 f2 mcu onboard.

It's a big tree tech tft  for cnc printers. Would be great to use it. Anyone know if this can be done?

**Comment by pingumacpenguin** [comment]
I've never tried it, but it *might* however the ADCs are different on the two architecture so you may need to do a little bit of digging through the STM32 f2 data sheet and modify the relevant ADC code. 

You could also ask on https://www.stm32duino.com/  - someone may already have given it a try.
