### ISSUE TITLE
Fail to compile

### ISSUE THREAD

**Issue by shaddow501** [pingumacpenguin/STM32-O-Scope#3]
Dear Sir

There is a problem to compile your code.
I get:

STM32-O-Scope:598: error: 'hour' was not declared in this scope

     if (hour(tt) < 10) {

                ^

STM32-O-Scope:601: error: 'hour' was not declared in this scope

     TFT.print(hour(tt));

                      ^

STM32-O-Scope:603: error: 'minute' was not declared in this scope

     if (minute(tt) < 10) {

                  ^

STM32-O-Scope:606: error: 'minute' was not declared in this scope

     TFT.print(minute(tt));

                        ^

STM32-O-Scope:608: error: 'second' was not declared in this scope

     if (second(tt) < 10) {

                  ^

STM32-O-Scope:611: error: 'second' was not declared in this scope

     TFT.print(second(tt));

                        ^

STM32-O-Scope:613: error: 'day' was not declared in this scope

     TFT.print(day(tt));

                     ^

STM32-O-Scope:615: error: 'month' was not declared in this scope

     TFT.print(month(tt));

                       ^

STM32-O-Scope:617: error: 'year' was not declared in this scope

     TFT.print(year(tt));

                      ^

STM32-O-Scope:867: error: 'setTime' was not declared in this scope

   setTime(thisArg.toInt());

                          ^

STM32-O-Scope:868: error: 'now' was not declared in this scope

   time_t tt = now();

                   ^

STM32-O-Scope:875: error: 'hour' was not declared in this scope

   if (hour(tt) < 10) {

              ^

STM32-O-Scope:878: error: 'hour' was not declared in this scope

   serial_debug.print(hour(tt));

                             ^

STM32-O-Scope:880: error: 'minute' was not declared in this scope

   if (minute(tt) < 10) {

                ^

STM32-O-Scope:883: error: 'minute' was not declared in this scope

   serial_debug.print(minute(tt));

                               ^

STM32-O-Scope:885: error: 'second' was not declared in this scope

   if (second(tt) < 10) {

                ^

STM32-O-Scope:888: error: 'second' was not declared in this scope

   serial_debug.print(second(tt));

                               ^

STM32-O-Scope:890: error: 'day' was not declared in this scope

   serial_debug.print(day(tt));

                            ^

STM32-O-Scope:892: error: 'month' was not declared in this scope

   serial_debug.print(month(tt));

                              ^

STM32-O-Scope:894: error: 'year' was not declared in this scope

   serial_debug.print(year(tt));

                             ^

exit status 1
'hour' was not declared in this scope

**Comment by pingumacpenguin** [comment]
The code is fine, it sounds like you have not included all of the libraries in the #includes  please read through -> http://stm32duino.com/viewtopic.php?f=19&t=107
.. if you don't find the answer, then ask the question in that thread.
